name: native_splash_screen
description: >
  A fully configurable native splash screen plugin for Flutter apps,
  supporting static linking, runtime animations, and CLI-based asset generation.
repository: https://github.com/anicine/native_splash_screen
version: 2.0.1

topics:
  - splash-screen
  - splash-image
  - splash-window

platforms:
  linux:
  windows:
  macos:

environment:
  sdk: ^3.7.2
  flutter: ">=3.10.0"

flutter:
  plugin:
    platforms:
      linux:
        default_package: native_splash_screen_linux
      windows:
        default_package: native_splash_screen_windows
      macos:
        default_package: native_splash_screen_macos

dependencies:
  flutter:
    sdk: flutter

  native_splash_screen_platform_interface: ">=2.0.0 <3.0.0"
  native_splash_screen_linux: ">=2.0.0 <3.0.0"
  native_splash_screen_windows: ">=2.0.0 <3.0.0"
  native_splash_screen_macos: ">=2.0.0 <3.0.0"

dev_dependencies:
  flutter_lints: ^5.0.0
