name: native_splash_screen
description: >
  A fully configurable native splash screen plugin for Flutter apps,
  supporting static linking, runtime animations, and CLI-based asset generation.
repository: https://github.com/anicine/native_splash_screen
version: 0.1.0

topics:
  - splash-screen
  - splash-image
  - splash-window

platforms:
  linux:
  windows:

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

flutter:
  plugin:
    platforms:
      linux:
        default_package: native_splash_screen_linux
      windows:
        default_package: native_splash_screen_windows

dependencies:
  flutter:
    sdk: flutter
  native_splash_screen_platform_interface: ">=0.1.0 <1.0.0"
  native_splash_screen_linux: ">=0.1.0 <1.0.0"
  native_splash_screen_windows: ">=0.1.0 <1.0.0"

dev_dependencies:
  flutter_lints: ^5.0.0
